import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased text-neutral-900`}
      >
        <header>
          <nav className="flex justify-center gap-8 py-4 bg-black border-b text-sm font-medium">
            <Link href="/" className="text-white hover:opacity-80">Home</Link>
            <Link href="/gallery" className="text-white hover:opacity-80">Gallery</Link>
            <Link href="/about" className="text-white hover:opacity-80">About</Link>
            <Link href="/blog" className="text-white hover:opacity-80">Blog</Link>
          </nav>
        </header>

        <main className="bg-neutral-50 min-h-screen text-neutral-900">
          {children}
        </main>
      </body>
    </html>
  );
}
